import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "@/styles/Home.module.css";
import { delay, motion } from "framer-motion";

import Layout from "@/components/Layout";
import Button from "@/components/Button";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <header className={styles.header}>
          <div className={styles.header__text}>
            <p className={styles.header__subtitle}>Luis Vasquez</p>
            <motion.h1
              initial={{ opacity: 0, y: 50 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.45 }}
            >
              <span className={styles.header__firstLine}>Diseñador</span>
              <span className={styles.header__secondLine}>
                UX{" "}
                <motion.img
                  src="/images/hand.png"
                  alt=""
                  animate={{ rotateZ: [null, -20, 20, 0] }}
                  transition={{ delay: 0.75 }}
                />
              </span>
            </motion.h1>
            <motion.p
              initial={{ opacity: 0, y: 25 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.45 }}
            >
              Me motiva crear experiencias de usuario atractivas, intuitivas y
              accesibles para aplicaciones web y móviles. Actualmente trabajando
              para una agencia de desarrollo de software.
            </motion.p>
          </div>
          <div className="header__cta">
            <Button>Contactame</Button>
          </div>
          <svg
            width="563"
            height="339"
            viewBox="0 0 563 339"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
            className={styles.header__svgLeft}
          >
            <line
              x1="94.5"
              y1="47"
              x2="94.5"
              y2="456"
              stroke="#818CF8"
              stroke-opacity="0.34"
            />
            <line x1="189.5" y1="129" x2="189.5" y2="403" stroke="#818CF8" />
            <line
              x1="284.5"
              y1="54"
              x2="284.5"
              y2="474"
              stroke="#818CF8"
              stroke-opacity="0.2"
            />
            <line
              x1="379.5"
              y1="27"
              x2="379.5"
              y2="474"
              stroke="url(#paint0_linear_45_14102)"
            />
            <line
              x1="-0.999112"
              y1="244.5"
              x2="562.001"
              y2="245.5"
              stroke="url(#paint1_linear_45_14102)"
            />
            <rect
              y="151"
              width="94"
              height="94"
              fill="#818CF8"
              fill-opacity="0.6"
            />
            <rect
              x="95"
              y="245"
              width="94"
              height="94"
              fill="#818CF8"
              fill-opacity="0.15"
            />
            <defs>
              <linearGradient
                id="paint0_linear_45_14102"
                x1="341.497"
                y1="85.1715"
                x2="355.338"
                y2="252.376"
                gradientUnits="userSpaceOnUse"
              >
                <stop stop-color="#818CF8" />
                <stop offset="1" stop-color="#818CF8" stop-opacity="0" />
              </linearGradient>
              <linearGradient
                id="paint1_linear_45_14102"
                x1="110.14"
                y1="252.703"
                x2="380.625"
                y2="292.565"
                gradientUnits="userSpaceOnUse"
              >
                <stop stop-color="#818CF8" />
                <stop offset="1" stop-color="#818CF8" stop-opacity="0" />
              </linearGradient>
            </defs>
          </svg>

          <svg
            width="868"
            height="605"
            viewBox="0 0 868 605"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
            className={styles.header__svg}
          >
            <line
              x1="304.5"
              y1="-166"
              x2="304.5"
              y2="566"
              stroke="#818CF8"
              stroke-opacity="0.59"
            />
            <line
              x1="399.5"
              y1="-146"
              x2="399.5"
              y2="587"
              stroke="#818CF8"
              stroke-opacity="0.34"
            />
            <line x1="494.5" y1="-199" x2="494.5" y2="534" stroke="#818CF8" />
            <line
              x1="589.5"
              y1="-125"
              x2="589.5"
              y2="605"
              stroke="#818CF8"
              stroke-opacity="0.2"
            />
            <line
              x1="684.5"
              y1="-125"
              x2="684.5"
              y2="605"
              stroke="url(#paint0_linear_46_14103)"
            />
            <line
              x1="208"
              y1="93.5"
              x2="771"
              y2="93.5"
              stroke="url(#paint1_linear_46_14103)"
            />
            <line
              x1="-4.37114e-08"
              y1="187.5"
              x2="622"
              y2="187.5"
              stroke="url(#paint2_linear_46_14103)"
            />
            <line
              x1="-4.37114e-08"
              y1="281.5"
              x2="622"
              y2="281.5"
              stroke="#818CF8"
              stroke-opacity="0.38"
            />
            <line
              x1="304.001"
              y1="375.5"
              x2="867.001"
              y2="376.5"
              stroke="url(#paint3_linear_46_14103)"
            />
            <line x1="220" y1="471.5" x2="843" y2="471.5" stroke="#818CF8" />
            <motion.rect
              x="495"
              y="187"
              width="94"
              height="94"
              fill="#818CF8"
              fill-opacity="0.6"
              initial={{ fillOpacity: 0.6 }}
              animate={{ fillOpacity: 0.1 }}
              transition={{
                repeat: Infinity,
                repeatType: "reverse",
                duration: 3,
                repeatDelay: 6,
              }}
            />
            <motion.rect
              x="305"
              y="282"
              width="94"
              height="94"
              fill="#818CF8"
              fill-opacity="0.6"
              initial={{ fillOpacity: 0.6 }}
              animate={{ fillOpacity: 0.1 }}
              transition={{
                repeat: Infinity,
                repeatType: "reverse",
                duration: 3,
                repeatDelay: 6,
              }}
            />
            <motion.rect
              x="210"
              y="377"
              width="94"
              height="94"
              fill="#818CF8"
              fill-opacity="0.1"
              initial={{ fillOpacity: 0.15 }}
              animate={{ fillOpacity: 0.6 }}
              transition={{
                repeat: Infinity,
                repeatType: "reverse",
                duration: 3,
                delay: 3,
              }}
            />
            <motion.rect
              x="401"
              y="94"
              width="94"
              height="94"
              fill="#818CF8"
              fill-opacity="0.15"
              initial={{ fillOpacity: 0.15 }}
              animate={{ fillOpacity: 0.6 }}
              transition={{
                repeat: Infinity,
                repeatType: "reverse",
                duration: 3,
                delay: 3,
              }}
            />
            <motion.rect
              x="210"
              y="-1"
              width="94"
              height="94"
              fill="#818CF8"
              fill-opacity="0.15"
              initial={{ fillOpacity: 0.15 }}
              animate={{ fillOpacity: 0.6 }}
              transition={{
                repeat: Infinity,
                repeatType: "reverse",
                duration: 3,
                delay: 3,
              }}
            />
            <motion.rect
              x="400"
              y="377"
              width="94"
              height="94"
              fill="#818CF8"
              fill-opacity="0.15"
              initial={{ fillOpacity: 0.15 }}
              animate={{ fillOpacity: 0.6 }}
              transition={{
                repeat: Infinity,
                repeatType: "reverse",
                duration: 3,
                delay: 3,
              }}
            />
            <defs>
              <linearGradient
                id="paint0_linear_46_14103"
                x1="646.497"
                y1="-29.9996"
                x2="682.997"
                y2="240"
                gradientUnits="userSpaceOnUse"
              >
                <stop stop-color="#818CF8" />
                <stop offset="1" stop-color="#818CF8" stop-opacity="0" />
              </linearGradient>
              <linearGradient
                id="paint1_linear_46_14103"
                x1="489.501"
                y1="94.002"
                x2="243.001"
                y2="205.002"
                gradientUnits="userSpaceOnUse"
              >
                <stop stop-color="#818CF8" />
                <stop offset="1" stop-color="#818CF8" stop-opacity="0" />
              </linearGradient>
              <linearGradient
                id="paint2_linear_46_14103"
                x1="311"
                y1="187.997"
                x2="76.4997"
                y2="216.497"
                gradientUnits="userSpaceOnUse"
              >
                <stop stop-color="#818CF8" />
                <stop offset="1" stop-color="#818CF8" stop-opacity="0" />
              </linearGradient>
              <linearGradient
                id="paint3_linear_46_14103"
                x1="415.14"
                y1="383.703"
                x2="685.625"
                y2="423.565"
                gradientUnits="userSpaceOnUse"
              >
                <stop stop-color="#818CF8" />
                <stop offset="1" stop-color="#818CF8" stop-opacity="0" />
              </linearGradient>
            </defs>
          </svg>
        </header>
        <section className={styles.caseStudies}>
          <article>
            <div className={styles.caseStudy__container}>
              <div className={styles.caseStudy__description}>
                <motion.h2
                  className={styles.caseStudy__title}
                  initial={{ opacity: 0, y: 50 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.45 }}
                >
                  Rediseño de Vagabundeando
                </motion.h2>
                <motion.p
                  initial={{ opacity: 0, y: 50 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.45 }}
                >
                  Ayudando a mejorar la experiencia de usuario y aumentar el
                  tiempo en el sitio de las personas usuarias
                </motion.p>
              </div>
              <Link href="/" className={styles.caseStudy__link}>
                Ver caso de estudio →
              </Link>
            </div>
            <motion.div
              className={styles.caseStudy__img}
              initial={{ opacity: 0, y: 50 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.65 }}
            >
              <Image
                src="/images/vagabundeando.png"
                height={379}
                width={1039}
              />
            </motion.div>
          </article>
          <article>
            <div className={styles.caseStudy__container}>
              <div className={styles.caseStudy__description}>
                <motion.h2
                  className={styles.caseStudy__title}
                  initial={{ opacity: 0, y: 50 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.45 }}
                >
                  Rediseño de Vagabundeando
                </motion.h2>
                <motion.p
                  initial={{ opacity: 0, y: 50 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.45 }}
                >
                  Ayudando a mejorar la experiencia de usuario y aumentar el
                  tiempo en el sitio de las personas usuarias
                </motion.p>
              </div>
              <Link href="/" className={styles.caseStudy__link}>
                Ver caso de estudio →
              </Link>
            </div>
            <motion.div
              className={styles.caseStudy__img}
              initial={{ opacity: 0, y: 50 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.65 }}
            >
              <Image src="/images/recipes.png" height={379} width={1039} />
            </motion.div>
          </article>
        </section>
        <Footer />
      </div>
    </Layout>
  );
}
