import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "@/styles/Home.module.scss";
import { motion } from "framer-motion";

import Layout from "@/components/Layout";
import Button from "@/components/Button";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Layout>
        <Head>
          <title>Luis Vásquez portafolio</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <meta name="description" content="Portafolio de diseñador UX" />
          <meta
            name="keywords"
            content="Diseñador UX, UI, CSS, Portafolio UX"
          />
          <meta name="author" content="Luis Vásquez" />
          <meta
            property="og:image"
            content="https://i.ibb.co/gzbNbL5/og-img-gray.png"
          />
          <meta
            property="og:url"
            content="https://ux-portfolio-eight.vercel.app/"
          />
          <meta property="og:type" content="website" />
          <meta property="og:title" content="Luis Vásquez Portafolio" />
          <meta
            property="og:description"
            content="Portafolio de diseñador UX"
          />
          <meta
            property="og:image"
            content="https://i.ibb.co/gzbNbL5/og-img-gray.png"
          />
          <meta name="twitter:card" content="summary_large_image" />
          <meta
            property="twitter:domain"
            content="ux-portfolio-eight.vercel.app"
          />
          <meta
            property="twitter:url"
            content="https://ux-portfolio-eight.vercel.app/"
          />
          <meta name="twitter:title" content="Luis Vásquez Portafolio" />
          <meta
            name="twitter:description"
            content="Portafolio de diseñador UX"
          />
          <meta
            name="twitter:image"
            content="https://i.ibb.co/gzbNbL5/og-img-gray.png"
          />
          <link rel="icon" href="/favicon.png" />
        </Head>
        <div>
          <header className={styles.header}>
            <div className={styles.header__text}>
              <p className={styles.header__overflowHidden}>
                <motion.span
                  className={styles.header__subtitle}
                  initial={{ y: 150 }}
                  animate={{ y: 0 }}
                  transition={{ duration: 0.75, delay: 0.15 }}
                >
                  Luis Vásquez
                </motion.span>
              </p>
              <h1>
                <span className={styles.header__clippy}>
                  <motion.span
                    className={styles.header__firstLine}
                    initial={{ y: 150 }}
                    animate={{ y: 0 }}
                    transition={{ duration: 0.75, delay: 0.15 }}
                  >
                    DISEÑADOR
                  </motion.span>
                </span>
                <span className={styles.header__clippy}>
                  <motion.span
                    className={styles.header__secondLine}
                    initial={{ y: 150 }}
                    animate={{ y: 0 }}
                    transition={{ duration: 0.75, delay: 0.15 }}
                  >
                    UX
                    <motion.img
                      src="/images/hand.png"
                      alt=""
                      animate={{ rotateZ: [null, -20, 20, 0] }}
                      transition={{ delay: 1.25 }}
                    />
                  </motion.span>
                </span>
              </h1>
              <p className={styles.header__overflowHidden}>
                <motion.span
                  initial={{ y: 150 }}
                  animate={{ y: 0 }}
                  transition={{ duration: 0.75, delay: 0.15 }}
                >
                  Soluciones creativas a problemas complejos. Actualmente
                  trabajando para una agencia de desarrollo de software. En mi
                  tiempo libre me gusta jugar con CSS, si, con CSS. ¿Tienes
                  algún proyecto en mente? Déjame un mensaje.
                </motion.span>
              </p>
            </div>

            <Button>Contáctame</Button>
          </header>
          <section className={styles.caseStudies}>
            <article>
              <div className={styles.caseStudies__container}>
                <div className={styles.caseStudies__description}>
                  <motion.h2
                    className={styles.caseStudies__title}
                    initial={{ opacity: 0, y: 50 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.45 }}
                  >
                    Rediseño de Vagabundeando
                  </motion.h2>
                  <motion.p
                    initial={{ opacity: 0, y: 50 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.45 }}
                  >
                    Mejorando la experiencia de usuario y aumentando el tiempo
                    en el sitio de las personas usuarias.
                  </motion.p>
                </div>
                <Link
                  href="/vagabundeando"
                  className={styles.caseStudies__link}
                >
                  Ver caso de estudio →
                </Link>
              </div>
              <motion.div
                className={styles.caseStudies__img}
                initial={{ opacity: 0, y: 50 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.65 }}
              >
                <Image
                  src="/images/vagabundeando.png"
                  height={379}
                  width={1039}
                  className={styles.covers}
                />
              </motion.div>
            </article>
            <article className={styles.mt__reset}>
              <div className={styles.caseStudies__container}>
                <div className={styles.caseStudies__description}>
                  <motion.h2
                    className={styles.caseStudies__title}
                    initial={{ opacity: 0, y: 50 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.45 }}
                  >
                    Aplicación de recetas
                  </motion.h2>
                  <motion.p
                    initial={{ opacity: 0, y: 50 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.45 }}
                  >
                    Ayudando a las personas a cocinar saludablemente.
                  </motion.p>
                </div>
                <Link href="/recipes" className={styles.caseStudies__link}>
                  Ver caso de estudio →
                </Link>
              </div>
              <motion.div
                className={styles.caseStudies__img}
                initial={{ opacity: 0, y: 50 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.65 }}
              >
                <Image
                  src="/images/recipes.png"
                  height={379}
                  width={1039}
                  className={styles.covers}
                />
              </motion.div>
            </article>
          </section>
        </div>
      </Layout>
      <Footer />
    </>
  );
}
