import Image from "next/image";
import Head from "next/head";

import Layout from "@/components/Layout";
import Footer from "@/components/Footer";
import styles from "@/styles/Cases.module.scss";

import cover from "../../public/images/vagabundeando.png";
import findingOne from "../../public/images/finding-1.png";
import findingTwo from "../../public/images/finding-2.png";
import findingThree from "../../public/images/finding-3.png";
import heuristica from "../../public/images/vaga-heuristica.png";
import home from "../../public/images/homepage.png";
import micrositio from "../../public/images/ciudad.png";
import cover1 from "../../public/images/cover-1.png";
import cover2 from "../../public/images/cover-2.png";
import cover3 from "../../public/images/cover-3.png";
import { motion } from "framer-motion";
import vaga1 from "../../public/images/vaga-1.png";
import vaga2 from "../../public/images/vaga-2.png";
import vaga3 from "../../public/images/vaga-3.png";
import vaga4 from "../../public/images/vaga-4.png";
import vaga5 from "../../public/images/vaga-5.png";
import vaga6 from "../../public/images/vaga-6.png";

import competidores from "../../public/images/competidores.png";

const container = {
  hidden: { opacity: 0 },
  show: {
    opacity: 1,
    transition: {
      staggerChildren: 0.3,
    },
  },
};

const item = {
  hidden: { opacity: 0 },
  show: { opacity: 1 },
};

export default function vagabundeando() {
  return (
    <Layout>
      <Head>
        <title>Rediseño de sitio web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className="container">
        <header className={styles.header}>
          <motion.h1
            className={styles.headingLarge}
            initial={{ y: 45, opacity: 0.4 }}
            animate={{ y: 0, opacity: 1 }}
          >
            Rediseño de Vagabundeando
          </motion.h1>
          <div className={styles.cover}>
            <motion.div
              className={styles.coverOne}
              initial={{ y: 80 }}
              animate={{ y: 0 }}
              transition={{ duration: 0.8 }}
            >
              <Image src={cover1} />
            </motion.div>
            <motion.div
              className={styles.coverTwo}
              initial={{ y: 100 }}
              animate={{ y: 0 }}
              transition={{ duration: 0.6 }}
            >
              <Image src={cover2} />
            </motion.div>
            <motion.div
              className={styles.coverThree}
              initial={{ y: 120 }}
              animate={{ y: 0 }}
              transition={{ duration: 0.45 }}
            >
              <Image src={cover3} />
            </motion.div>
          </div>
          <div className={styles.header__description}>
            <div>
              <h2 className={styles.header__subtitle}>Overview</h2>
              <p>
                Vagabundeando es un sitio web que le permite a turistas y
                locales encontrar información sobre lugares y actividades para
                realizar en México.
              </p>
            </div>
            <div>
              <h2 className={styles.header__subtitle}>
                Planteamiento de problema
              </h2>
              <p>
                Actualmente, las personas usuarias estaban llegando al sitio web
                a través de diferentes canales, pero el tiempo de permanencia en
                la página era muy bajo. Esto estaba afectando negativamente los
                ingresos del negocio.
              </p>
            </div>

            <div>
              <h2 className={styles.header__subtitle}>Usuarios</h2>
              <p>
                Mediante entrevistas con el cliente y análisis de analíticas se
                identificaron 3 grupos principales:
              </p>
              <ul>
                <li>
                  Turistas que buscan encontrar toda la información necesaria
                  para aprovechar su estadía al máximo.
                </li>
                <li>
                  Locales que quieren conocer nuevos lugares y practicar
                  actividades interesantes.
                </li>
                <li>
                  Dueños de pequeños y medianos negocios locales que quieran dar
                  a conocer sus servicios.
                </li>
              </ul>
            </div>

            <div>
              <h2 className={styles.header__subtitle}>Rol</h2>
              <p>
                Diseñador UX/UI (investigación con usuarios, arquitectura de
                información, wireframe, UI kit y prototipado).
              </p>
            </div>

            <div>
              <h2 className={styles.header__subtitle}>
                Alcance y restricciones
              </h2>
              <p>Tiempo reducido para llevar a cabo este proyecto, 2 semanas</p>
            </div>
          </div>
        </header>
        <main className={styles.sections}>
          <section className={styles.articles}>
            <h2>Proceso</h2>
            <article>
              <h3>Entendiendo el estado actual</h3>
              <div className={styles.arrow__container}>
                <motion.svg
                  width="130"
                  height="130"
                  viewBox="0 0 130 130"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                  className={styles.arrowOne}
                  initial={{ opacity: 0 }}
                  whileInView={{ opacity: 1 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.45, delay: 0.15 }}
                >
                  <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M125.918 5.8458C116.987 66.971 62.1418 96.6614 4.8859 103.412C3.90271 103.53 3.19581 104.423 3.31361 105.406C3.43141 106.389 4.32394 107.096 5.30712 106.978C64.167 100.041 120.29 69.2001 129.47 6.36226C129.615 5.3836 128.935 4.47291 127.952 4.32793C126.973 4.18294 126.063 4.86261 125.918 5.8458Z"
                    fill="black"
                  />
                  <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M6.17112 105.069C8.71744 103.207 11.9389 100.906 12.2968 100.634C21.9973 93.2667 30.0349 84.7895 37.1121 74.8444C37.6875 74.0379 37.4971 72.9143 36.6906 72.3388C35.8842 71.7634 34.7606 71.9538 34.1852 72.7603C27.3255 82.4064 19.5326 90.6298 10.1221 97.7749C9.57386 98.1917 2.32897 103.361 0.942538 104.517C0.371655 104.988 0.195077 105.432 0.163361 105.541C-0.0269333 106.112 0.0863017 106.56 0.240349 106.886C0.417051 107.253 0.856425 107.788 1.70822 108.06C2.60079 108.341 4.58538 108.468 5.08377 108.54C12.6004 109.655 21.0867 110.244 28.8117 112.382C36.1788 114.421 42.8616 117.874 47.1478 124.792C47.6688 125.635 48.7789 125.893 49.6216 125.372C50.4643 124.851 50.7227 123.741 50.2017 122.898C45.4081 115.164 38.0046 111.2 29.7721 108.921C22.0923 106.796 13.6832 106.152 6.17112 105.069Z"
                    fill="black"
                  />
                </motion.svg>
                <motion.svg
                  width="187"
                  height="187"
                  viewBox="0 0 187 187"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                  className={styles.arrowTwo}
                  initial={{ opacity: 0 }}
                  whileInView={{ opacity: 1 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.45, delay: 0.25 }}
                >
                  <g clip-path="url(#clip0_307_320)">
                    <path
                      fill-rule="evenodd"
                      clip-rule="evenodd"
                      d="M87.5277 134.471C108.631 145.907 132.767 154.306 156.697 152.661C165.404 152.063 173.464 149.552 181.739 147.056C182.319 146.882 182.65 146.267 182.476 145.683C182.299 145.1 181.683 144.769 181.1 144.946C172.985 147.393 165.085 149.874 156.546 150.461C132.956 152.083 109.177 143.73 88.3927 132.434L88.5407 132.1C90.1573 128.481 89.156 123.199 86.5148 117.655C82.7301 109.708 75.6832 101.17 69.3415 96.4532C66.4914 94.3345 63.7603 92.9878 61.508 92.7063C59.7521 92.4857 58.2458 92.8804 57.0819 93.9311C54.6033 96.1717 54.6903 99.9941 56.6552 104.426C60.7621 113.696 72.8243 125.904 79.3663 129.819C81.4095 131.041 83.4877 132.242 85.5977 133.412C85.3307 134.056 85.0665 134.686 84.7821 135.287C83.9665 136.996 82.9652 138.491 81.0351 139.516C78.0254 141.109 74.4178 141.385 70.726 140.973C64.9648 140.325 59.0004 137.983 54.6091 135.972C30.1537 124.769 18.0422 105.337 11.5467 85.8306C4.99022 66.1293 4.13112 46.3351 2.18944 34.6589C2.09076 34.0581 1.52189 33.6547 0.921104 33.7534C0.320314 33.8521 -0.0860165 34.4209 0.0155664 35.0217C1.96886 46.7734 2.85406 66.6953 9.45694 86.5272C16.1208 106.553 28.5865 126.475 53.689 137.977C58.2632 140.073 64.48 142.491 70.4792 143.164C74.6325 143.628 78.6813 143.257 82.0684 141.463C85.1072 139.852 86.3145 137.339 87.5277 134.471ZM86.4539 131.366L86.5293 131.2C87.9428 128.037 86.8341 123.451 84.5238 118.604C80.8871 110.968 74.1217 102.757 68.0238 98.2237C65.9341 96.668 63.9344 95.5506 62.1756 95.0804C60.7244 94.6944 59.4648 94.7496 58.5621 95.568C57.7059 96.3372 57.3663 97.3965 57.3808 98.63C57.3953 100.078 57.8772 101.741 58.6695 103.532C62.6167 112.439 74.2117 124.165 80.4982 127.927C82.4515 129.093 84.4367 130.243 86.4539 131.366Z"
                      fill="black"
                    />
                    <path
                      fill-rule="evenodd"
                      clip-rule="evenodd"
                      d="M184.536 143.644C184.441 144.117 184.118 144.712 183.764 145.347C182.923 146.862 181.724 148.476 181.19 149.26C180.848 149.765 180.981 150.45 181.483 150.792C181.988 151.135 182.673 151.004 183.016 150.499C183.669 149.538 185.262 147.385 186.118 145.6C186.577 144.642 186.815 143.757 186.763 143.121C186.675 142.039 185.819 141.362 184.121 141.403C182.113 141.452 178.383 142.46 175.26 141.249C174.694 141.029 174.053 141.313 173.835 141.879C173.615 142.448 173.896 143.086 174.465 143.307C177.443 144.459 180.914 143.905 183.251 143.673C183.695 143.629 184.223 143.635 184.536 143.644Z"
                      fill="black"
                    />
                  </g>
                  <defs>
                    <clipPath id="clip0_307_320">
                      <rect width="187" height="187" fill="white" />
                    </clipPath>
                  </defs>
                </motion.svg>

                <Image
                  src={heuristica}
                  alt="diferentes pantallas de sitio web de vagabundeando donde se encontraron problemas de usabilidad"
                />
              </div>

              <p>
                Para entender el estado actual del sitio web, lleve a cabo un
                análisis heurístico, donde compare el sitio actual con las
                heurísticas de Nielsen y lograr identificar problemas de
                usabilidad que pudieran estar presentes. Algunos de los
                problemas encontrados fueron: excesivos tiempos de carga, falta
                de organización y jerarquía del contenido, navegación confusa,
                pobre accesibilidad, inconsistencias de elementos, pobre manejo
                de errores.
              </p>
            </article>
            <article>
              <h3>Obteniendo feedback de los usuarios</h3>
              <p>
                La etapa previa me había ayudado a identificar algunos problemas
                de usabilidad, ahora era importante saber si las personas
                usuarias podrían lograr sus objetivos al hacer uso del sitio
                web, para ello realicé una prueba de usabilidad en remoto, no
                moderada, con 7 usuarios representativos. Algunos hallazgos
                fueron:
              </p>
              <ul className={styles.findings}>
                <li className={styles.usability__finding}>
                  <motion.div
                    className={styles.finding__imgContainer}
                    initial={{ opacity: 0, y: 50 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.45 }}
                  >
                    <Image src={findingOne} className={styles.finding__img} />
                  </motion.div>
                  <div className={styles.usability__description}>
                    <p>
                      La barra de búsqueda está poco optimizada y no maneja los
                      casos de error
                    </p>
                    <p className={styles.usability__quote}>
                      <svg
                        width="23"
                        height="21"
                        viewBox="0 0 23 21"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          d="M20.25 20.25C20.8302 20.25 21.3866 20.0195 21.7968 19.6093C22.207 19.1991 22.4375 18.6427 22.4375 18.0625V12.7206C22.4375 12.1405 22.207 11.5841 21.7968 11.1738C21.3866 10.7636 20.8302 10.5331 20.25 10.5331H17.2138C17.2138 9.76531 17.2597 8.99531 17.3494 8.2275C17.485 7.41375 17.7125 6.68969 18.0275 6.0575C18.3447 5.42313 18.7516 4.92656 19.2503 4.56344C19.7469 4.15656 20.3791 3.95313 21.1491 3.95313V0.5625C19.8825 0.5625 18.7756 0.83375 17.8241 1.37625C16.8808 1.91325 16.0698 2.65474 15.4506 3.54625C14.8292 4.52913 14.3712 5.60621 14.0944 6.73563C13.8155 7.98198 13.679 9.25597 13.6875 10.5331V18.0625C13.6875 18.6427 13.918 19.1991 14.3282 19.6093C14.7385 20.0195 15.2949 20.25 15.875 20.25H20.25ZM7.12501 20.25C7.70517 20.25 8.26157 20.0195 8.67181 19.6093C9.08204 19.1991 9.31251 18.6427 9.31251 18.0625V12.7206C9.31251 12.1405 9.08204 11.5841 8.67181 11.1738C8.26157 10.7636 7.70517 10.5331 7.12501 10.5331H4.08876C4.08876 9.76531 4.1347 8.99531 4.22439 8.2275C4.36001 7.41375 4.58751 6.68969 4.90251 6.0575C5.2197 5.42313 5.62658 4.92656 6.12533 4.56344C6.62189 4.15656 7.25408 3.95313 8.02408 3.95313V0.5625C6.75751 0.5625 5.65064 0.83375 4.69908 1.37625C3.7558 1.91325 2.94479 2.65474 2.32564 3.54625C1.70422 4.52913 1.2462 5.60621 0.969388 6.73563C0.690451 7.98198 0.553951 9.25597 0.562513 10.5331V18.0625C0.562513 18.6427 0.792981 19.1991 1.20322 19.6093C1.61345 20.0195 2.16985 20.25 2.75001 20.25H7.12501Z"
                          fill="black"
                        />
                      </svg>
                      Intento buscar un lugar pero no me muestra nada, no se que
                      hacer”
                    </p>
                  </div>
                </li>
                <li className={styles.usability__finding}>
                  <motion.div
                    className={styles.finding__imgContainer}
                    initial={{ opacity: 0, y: 50 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.45 }}
                  >
                    <Image src={findingTwo} className={styles.finding__img} />
                  </motion.div>
                  <div className={styles.usability__description}>
                    <p>La navegación del sitio web es poco intuitiva</p>
                    <p className={styles.usability__quote}>
                      <svg
                        width="23"
                        height="21"
                        viewBox="0 0 23 21"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          d="M20.25 20.25C20.8302 20.25 21.3866 20.0195 21.7968 19.6093C22.207 19.1991 22.4375 18.6427 22.4375 18.0625V12.7206C22.4375 12.1405 22.207 11.5841 21.7968 11.1738C21.3866 10.7636 20.8302 10.5331 20.25 10.5331H17.2138C17.2138 9.76531 17.2597 8.99531 17.3494 8.2275C17.485 7.41375 17.7125 6.68969 18.0275 6.0575C18.3447 5.42313 18.7516 4.92656 19.2503 4.56344C19.7469 4.15656 20.3791 3.95313 21.1491 3.95313V0.5625C19.8825 0.5625 18.7756 0.83375 17.8241 1.37625C16.8808 1.91325 16.0698 2.65474 15.4506 3.54625C14.8292 4.52913 14.3712 5.60621 14.0944 6.73563C13.8155 7.98198 13.679 9.25597 13.6875 10.5331V18.0625C13.6875 18.6427 13.918 19.1991 14.3282 19.6093C14.7385 20.0195 15.2949 20.25 15.875 20.25H20.25ZM7.12501 20.25C7.70517 20.25 8.26157 20.0195 8.67181 19.6093C9.08204 19.1991 9.31251 18.6427 9.31251 18.0625V12.7206C9.31251 12.1405 9.08204 11.5841 8.67181 11.1738C8.26157 10.7636 7.70517 10.5331 7.12501 10.5331H4.08876C4.08876 9.76531 4.1347 8.99531 4.22439 8.2275C4.36001 7.41375 4.58751 6.68969 4.90251 6.0575C5.2197 5.42313 5.62658 4.92656 6.12533 4.56344C6.62189 4.15656 7.25408 3.95313 8.02408 3.95313V0.5625C6.75751 0.5625 5.65064 0.83375 4.69908 1.37625C3.7558 1.91325 2.94479 2.65474 2.32564 3.54625C1.70422 4.52913 1.2462 5.60621 0.969388 6.73563C0.690451 7.98198 0.553951 9.25597 0.562513 10.5331V18.0625C0.562513 18.6427 0.792981 19.1991 1.20322 19.6093C1.61345 20.0195 2.16985 20.25 2.75001 20.25H7.12501Z"
                          fill="black"
                        />
                      </svg>
                      ¿Por qué colocar los links para navegar abajo? Casi no los
                      encuentro”
                    </p>
                  </div>
                </li>
                <li className={styles.usability__finding}>
                  <motion.div
                    className={styles.finding__imgContainer}
                    initial={{ opacity: 0, y: 50 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.45 }}
                  >
                    <Image src={findingThree} className={styles.finding__img} />
                  </motion.div>
                  <div className={styles.usability__description}>
                    <p>
                      Los elementos de la interfaz tienen problemas de
                      affordance
                    </p>
                    <p className={styles.usability__quote}>
                      <svg
                        width="23"
                        height="21"
                        viewBox="0 0 23 21"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          d="M20.25 20.25C20.8302 20.25 21.3866 20.0195 21.7968 19.6093C22.207 19.1991 22.4375 18.6427 22.4375 18.0625V12.7206C22.4375 12.1405 22.207 11.5841 21.7968 11.1738C21.3866 10.7636 20.8302 10.5331 20.25 10.5331H17.2138C17.2138 9.76531 17.2597 8.99531 17.3494 8.2275C17.485 7.41375 17.7125 6.68969 18.0275 6.0575C18.3447 5.42313 18.7516 4.92656 19.2503 4.56344C19.7469 4.15656 20.3791 3.95313 21.1491 3.95313V0.5625C19.8825 0.5625 18.7756 0.83375 17.8241 1.37625C16.8808 1.91325 16.0698 2.65474 15.4506 3.54625C14.8292 4.52913 14.3712 5.60621 14.0944 6.73563C13.8155 7.98198 13.679 9.25597 13.6875 10.5331V18.0625C13.6875 18.6427 13.918 19.1991 14.3282 19.6093C14.7385 20.0195 15.2949 20.25 15.875 20.25H20.25ZM7.12501 20.25C7.70517 20.25 8.26157 20.0195 8.67181 19.6093C9.08204 19.1991 9.31251 18.6427 9.31251 18.0625V12.7206C9.31251 12.1405 9.08204 11.5841 8.67181 11.1738C8.26157 10.7636 7.70517 10.5331 7.12501 10.5331H4.08876C4.08876 9.76531 4.1347 8.99531 4.22439 8.2275C4.36001 7.41375 4.58751 6.68969 4.90251 6.0575C5.2197 5.42313 5.62658 4.92656 6.12533 4.56344C6.62189 4.15656 7.25408 3.95313 8.02408 3.95313V0.5625C6.75751 0.5625 5.65064 0.83375 4.69908 1.37625C3.7558 1.91325 2.94479 2.65474 2.32564 3.54625C1.70422 4.52913 1.2462 5.60621 0.969388 6.73563C0.690451 7.98198 0.553951 9.25597 0.562513 10.5331V18.0625C0.562513 18.6427 0.792981 19.1991 1.20322 19.6093C1.61345 20.0195 2.16985 20.25 2.75001 20.25H7.12501Z"
                          fill="black"
                        />
                      </svg>
                      No se donde dar click para continuar”
                    </p>
                  </div>
                </li>
              </ul>
            </article>
            <article>
              <h3>Identificando oportunidades de mejora</h3>
              <Image
                src={competidores}
                className={styles.competidores}
                alt="Competidores principales de Vagabundeando: Airbnb, Get yout guide, Tripadvisor y Yelp"
              />
              <p>
                En esta etapa llevé a cabo un análisis competitivo para entender
                en mayor profundidad el mercado donde se encontraba el producto,
                esto también me iba a ayudar a identificar oportunidades de
                mejora en aspectos como: funcionalidad, propuesta de valor,
                diseño visual, tono y voz. Para ello seleccioné 4 competidores y
                procedí a evaluar la experiencia general en cada uno de ellos.
                Algunos de los gaps fueron:
              </p>
              <ul>
                <li>
                  Gran parte de los sitios web de los competidores tienen
                  problemas de accesibilidad.
                </li>
                <li>Las barras de búsqueda no están optimizadas.</li>
                <li>
                  Contenidos irrelevantes, desactualizados y demasiado
                  descriptivo que llegan a saturar.
                </li>
                <li>Diseños poco cuidados e intuitivos.</li>
              </ul>
            </article>
            <article>
              <h3>Aplicando las mejoras</h3>
              <article>
                <h4>Pagina de inicio</h4>
                <p>
                  Se creó un diseño minimalista eliminando elementos que añadían
                  ruido visual y se mejoró la jerarquía, haciendo uso de
                  colores, tamaños, y espaciados. Se optimizó la barra de
                  búsqueda para mostrar sugerencias mientras se realiza la
                  búsqueda y manejar los casos de error. También se agregaron
                  categorías de fácil acceso basadas en la data recolectada para
                  motivar a los usuarios a navegar por el sitio.
                </p>
                <motion.div
                  className={styles.mt}
                  initial={{ opacity: 0 }}
                  whileInView={{ opacity: 1 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.45 }}
                >
                  <Image src={home} className={styles.outline__img} />
                </motion.div>
              </article>

              <article>
                <h4>Locales</h4>
                <p>
                  Los elementos de la interfaz se ubicaron donde los usuarios
                  esperaban encontrarlos, alineando los modelos de mentales de
                  estos con el diseño, logrando una interfaz que fuera más
                  intuitiva y fácil de usar. Se mejoró la organización del
                  contenido y se eliminó aquel que no era relevante. Las
                  acciones más importantes como los botones se destacaron y se
                  mejoró su affordance.
                </p>
                <motion.div
                  className={styles.mt}
                  initial={{ opacity: 0 }}
                  whileInView={{ opacity: 1 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.45 }}
                >
                  <Image src={micrositio} className={styles.outline__img} />
                </motion.div>
              </article>
            </article>
            <article>
              <h3>Pantallas principales</h3>
              <motion.div
                className={styles.grid}
                variants={container}
                initial="hidden"
                whileInView="show"
                viewport={{ once: true }}
              >
                <motion.div variants={item}>
                  <Image src={vaga1} />
                </motion.div>
                <motion.div variants={item}>
                  <Image src={vaga2} />
                </motion.div>
                <motion.div variants={item}>
                  <Image src={vaga3} />
                </motion.div>
                <motion.div variants={item}>
                  <Image src={vaga4} />
                </motion.div>
                <motion.div variants={item}>
                  <Image src={vaga5} />
                </motion.div>
                <motion.div variants={item}>
                  <Image src={vaga6} />
                </motion.div>
              </motion.div>
            </article>
          </section>
          <section>
            <h2>Resultados</h2>
            <ul>
              <li>
                Incremento en el tiempo que pasan las personas usuarias en el
                sitio web.
              </li>
              <li>Incremento en el número de visitas.</li>
            </ul>
          </section>
          <section>
            <h2>Lo que aprendí</h2>
            <ul>
              <li>
                Es importante poder adaptarnos a los requerimientos específicos
                del proyecto, y no atarse a usar siempre un mismo framework de
                trabajo, esto nos permitirá ahorrar recursos y ser más
                eficientes.
              </li>
              <li>
                Observar a los usuarios interactuar con el producto y escuchar
                su feedback es esencial para poder mejorar la experiencia en el
                sitio y mantenerlo relevante para ellos.
              </li>
              <li>
                Presentar la información de manera clara y organizada es
                esencial para ayudar a los usuarios a encontrar fácilmente la
                información que necesitan.
              </li>
              <li>
                Muchos usuarios acceden a sitios web desde sus dispositivos
                móviles, por lo que es importante asegurarse de que el sitio sea
                accesible y fácil de usar en una variedad de dispositivos.
              </li>
            </ul>
          </section>
          <section>
            <h2>Próximos pasos</h2>
            <ul>
              <li>
                Conducir un segundo round de pruebas de usabilidad para validar
                los cambios realizados.
              </li>
              <li>
                Monitorear cómo los usuarios están interactuando con el sitio a
                través de herramientas de analítica para poder identificar áreas
                de mejora.
              </li>
              <li>
                Evaluar la accesibilidad para asegurar que el sitio sea fácil de
                usar para todos, incluyendo personas con discapacidad.
              </li>
            </ul>
          </section>
        </main>
        <Footer />
      </div>
    </Layout>
  );
}
