import Footer from "@/components/Footer";
import Layout from "@/components/Layout";
import styles from "@/styles/ColegioIdeal.module.scss";

import Image from "next/image";
import Head from "next/head";
import Link from "next/link";
import Navbar from "@/components/Navbar";

import { motion } from "framer-motion";

import pin from "../../../public/images/pinBlue.png";
import susana from "../../../public/images/susana.png";
import cover from "../../../public/images/tucolegiocover.png";
import wireOne from "../../../public/images/colegio-wire-1.png";
import wireTwo from "../../../public/images/colegio-wire-2.png";
import wireThree from "../../../public/images/colegio-wire-3.png";
import shotOne from "../../../public/images/shot-one.png";
import shotTwo from "../../../public/images/shot-two.png";
import MobileNav from "@/components/MobileNav";

export default function mercantil() {
  return (
    <>
      <nav className={styles.nav}>
        <Link href="/" className={styles.nav__link}>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            strokeWidth={1.5}
            stroke="currentColor"
            className="w-6 h-6"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M6.75 15.75L3 12m0 0l3.75-3.75M3 12h18"
            />
          </svg>
          Regresar a inicio
        </Link>
      </nav>
      <Navbar />

      <motion.div
        class={styles.header__coverEdit}
        initial={{ opacity: 0 }}
        whileInView={{ opacity: 1 }}
        transition={{ duration: 1.1 }}
      >
        <div class={styles.header__coverEditInner}>
          <motion.h1
            initial={{ y: 45, opacity: 0.4 }}
            whileInView={{ y: 0, opacity: 1 }}
            transition={{ duration: 0.65 }}
            id="top"
            class={styles.header__title}
          >
            Tu colegio ideal
          </motion.h1>
          <Image src={cover} className={styles.cover__img} />
        </div>
      </motion.div>

      <Layout>
        <Head>
          <title>Tu colegio ideal</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.png" />
        </Head>

        <div>
          <header className={styles.header}>
            <div className={styles.header__description}>
              <Image src={pin} alt="" className={styles.header__pin} />
              <div>
                <h2 className={styles.header__subtitle} id="problema">
                  Visión general
                </h2>
                <p>
                  <b>Tu colegio ideal</b> es una plataforma que le permite a los
                  padres encontrar diferentes colegios según sus preferencias,
                  leer comentarios y calificaciones de otros padres, y comparar
                  las opciones disponibles.
                </p>
              </div>
              <div>
                <h2 className={styles.header__subtitle} id="solucion">
                  Planteamiento del problema
                </h2>
                <p>
                  Cuando los padres buscan un colegio para sus hijos, deben de
                  considerar diversos factores como la calidad educativa, el
                  ambiente escolar, la ubicación, el costo, el proyecto
                  educativo, etc. Sin embargo, no siempre cuentan con los medios
                  o las herramientas para acceder a esta información de forma
                  fácil y confiable para poder tomar una decisión informada.
                  Esto les genera estrés, frustración y pérdida de tiempo.
                </p>
              </div>

              <div>
                <h2 className={styles.header__subtitle} id="rol">
                  Rol
                </h2>
                <p>
                  Diseñador UX/UI (investigación con usuarios, arquitectura de
                  información, wireframe, UI kit y prototipado).
                </p>
              </div>

              <div>
                <h2 className={styles.header__subtitle} id="rol">
                  Equipo
                </h2>
                <p>
                  1 product owner, 1 project manager, 2 desarrolladores
                  fullstack y 1 diseñador UX/UI.
                </p>
              </div>

              <div>
                <h2 className={styles.header__subtitle} id="rol">
                  Duración
                </h2>
                <p>3 meses.</p>
              </div>
            </div>
          </header>

          <section className={styles.section}>
            <h2 className={styles.icon__heading}>Proceso</h2>
            <div className={styles.section__inner}>
              <p>
                Para entender mejor el espacio del problema e identificar áreas
                donde iba a necesitar realizar investigación, realicé una
                <b> investigación secundaria</b>, consultando investigaciones
                previas relacionadas con el proyecto, con los hallazgos
                obtenidos logré acotar el alcance de mi siguiente investigación.
                Llevé a cabo una <b>encuesta</b> con el objetivo de conocer las
                preferencias y retos de los padres al realizar la búsqueda de
                colegios. La encuesta tenía preguntas tanto abiertas como
                cerradas y participaron unas 35 personas.
              </p>
              <Image src={susana} alt="" className={styles.caseImg} />
              <p>
                Durante esta etapa, también, realicé un{" "}
                <b>análisis competitivo</b> para entender como el producto se
                posicionaba frente a sus principales competidores, cuáles eran
                sus ventajas y desventajas con respecto a estos.
              </p>
              <p>
                Luego se procedió a la etapa de definición, se estableció la
                arquitectura de información, los flujos y wireframes iniciales,
                todo esto con una constante revisión por parte del cliente y el
                product owner.
              </p>

              <div className={styles.gallery}>
                <Image src={wireOne} alt="" />
                <Image src={wireTwo} alt="" />
                <Image src={wireThree} alt="" />
              </div>
            </div>
          </section>
          <section className={styles.finalDesign}>
            <h2>Diseños finales</h2>
            <div className={styles.video__gallery}>
              <div
                className={`${styles.finalDesign__block} ${styles.img__presentation}`}
              >
                <video
                  src={"/images/colegio-main-flow.mp4"}
                  autoPlay
                  muted
                  loop
                  className={styles.finalDesign__video}
                ></video>
              </div>
              <div className={styles.img__presentation}>
                <Image src={shotOne} alt="" />
              </div>

              <div className={styles.img__presentation}>
                <Image src={shotTwo} alt="" />
              </div>
              <div className={styles.img__presentation}>
                <video src={"/images/shot-3.mp4"} autoPlay muted loop></video>
              </div>
              <div className={styles.img__presentation}>
                <video src={"/images/shot-5.mp4"} autoPlay muted loop></video>
              </div>
            </div>
          </section>

          <section>
            <h2>Resultados</h2>
            <p>
              Se han registrado una gran cantidad de usuarios en el primer mes
              de lanzamiento, recibiendo feedback muy favorable por parte de los
              padres, quienes han valorado la variedad de opciones y la
              transparencia de la información. Asimismo, se han logrado alianzas
              con diferentes colegios, quienes han visto en la plataforma una
              oportunidad para dar a conocer su oferta educativa y atraer a
              nuevos alumnos.
            </p>
          </section>
        </div>
      </Layout>
      <Footer />

      <MobileNav />
    </>
  );
}
