import Image from "next/image";
import Head from "next/head";
import Link from "next/link";

import { motion } from "framer-motion";

import Footer from "@/components/Footer";
import Layout from "@/components/Layout";
import styles from "@/styles/Recipes.module.scss";
import Navbar from "@/components/Navbar";

import wireframeOne from "../../../public/images/usabilityone.png";
import wireframetwo from "../../../public/images/usabilitytwo.png";
import refineOne from "../../../public/images/refineOne.png";
import refineTwo from "../../../public/images/refineTwo.png";
import sitemap from "../../../public/images/sitemap-recipe.png";
import flow from "../../../public/images/flow-recipe.png";
import journeymap from "../../../public/images/journeymap-recipe.png";
import persona from "../../../public/images/user-persona.png";
import wire1 from "../../../public/images/wire1.png";
import wire2 from "../../../public/images/wire2.png";
import wire3 from "../../../public/images/wire3.png";
import wire4 from "../../../public/images/wire4.png";
import wire5 from "../../../public/images/wire5.png";
import wire6 from "../../../public/images/wire6.png";
import wire7 from "../../../public/images/wire7.png";
import final1 from "../../../public/images/final1.png";
import final2 from "../../../public/images/final2.png";
import final3 from "../../../public/images/final3.png";
import final4 from "../../../public/images/final4.png";
import final5 from "../../../public/images/final5.png";
import final6 from "../../../public/images/final6.png";
import final7 from "../../../public/images/final7.png";
import final8 from "../../../public/images/final8.png";
import pin from "../../../public/images/pin.png";
import eatWell from "../../../public/images/eatwell-portada-bg.png";

import MobileNav from "@/components/MobileNav";

const container = {
  hidden: { opacity: 0 },
  show: {
    opacity: 1,
    transition: {
      staggerChildren: 0.3,
    },
  },
};

const item = {
  hidden: { opacity: 0 },
  show: { opacity: 1 },
};

export default function recipes() {
  return (
    <>
      <nav className={styles.nav}>
        <Link href="/" className={styles.nav__link}>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            strokeWidth={1.5}
            stroke="currentColor"
            className="w-6 h-6"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M6.75 15.75L3 12m0 0l3.75-3.75M3 12h18"
            />
          </svg>
          Regresar a inicio
        </Link>
      </nav>
      <Navbar />

      <motion.div
        class={styles.header__coverEdit}
        initial={{ opacity: 0 }}
        whileInView={{ opacity: 1 }}
        transition={{ duration: 1.1 }}
      >
        <div class={styles.header__coverEditInner}>
          <motion.h1
            initial={{ y: 45, opacity: 0.4 }}
            whileInView={{ y: 0, opacity: 1 }}
            transition={{ duration: 0.65 }}
            className={styles.header__headingLarge}
            id="top"
          >
            EatWell
          </motion.h1>
          <Image src={eatWell} />
        </div>
      </motion.div>

      <Layout>
        <Head>
          <title>EatWell</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.png" />
        </Head>

        <div>
          <header className={styles.header}>
            <ul className={styles.tableContent}>
              <p className={styles.tableContent__title}>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth="1.5"
                  stroke="currentColor"
                  class="w-6 h-6"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M8.25 6.75h12M8.25 12h12m-12 5.25h12M3.75 6.75h.007v.008H3.75V6.75zm.375 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zM3.75 12h.007v.008H3.75V12zm.375 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm-.375 5.25h.007v.008H3.75v-.008zm.375 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z"
                  />
                </svg>
                Tabla de contenidos
              </p>
              <li>
                <Link href="#problema">Planteamiento de problema</Link>
              </li>

              <li>
                <Link href="#solucion">Solución</Link>
              </li>

              <li>
                <Link href="#rol">Rol</Link>
              </li>

              <li>
                <Link href="#empatizando">Empatizando</Link>
              </li>
              <li>
                <Link href="#ideacion">Ideación</Link>
              </li>
              <li>
                <Link href="#refinando">Refinando</Link>
              </li>
              <li>
                <Link href="#aprendido">Lo que aprendí</Link>
              </li>
              <li>
                <Link href="#proximo">Próximos pasos</Link>
              </li>
            </ul>

            <div className={styles.header__description}>
              <Image src={pin} alt="" className={styles.header__pin} />
              <div>
                <h2 className={styles.header__subtitle} id="problema">
                  Planteamiento del problema
                </h2>
                <p>
                  Debido a las ajetreadas rutinas diarias, las personas ha
                  adoptado malos hábitos alimentarios que afectan a su salud.
                  Cuando intentan mejorar estos hábitos y cocinar de forma
                  saludable, les resulta difícil encontrar recetas que se
                  ajusten a sus necesidades específicas, lo que les hace
                  sentirse frustrados.
                </p>
              </div>
              <div>
                <h2 className={styles.header__subtitle} id="solucion">
                  Solución
                </h2>
                <p>
                  Crear una aplicación que le permita a las personas usuarias
                  encontrar fácilmente recetas que hayan sido previamente
                  evaluadas por profesionales de la salud, que puedan elaborarse
                  rápidamente y que tenga en cuenta sus preferencias.
                </p>
              </div>
              <div>
                <h2 className={styles.header__subtitle} id="rol">
                  Rol
                </h2>
                <p>
                  Diseñador UX/UI (investigación con usuarios, arquitectura de
                  información, wireframe, UI kit y prototipado).
                </p>
              </div>
            </div>
            <div className={styles.coverTwo}>
              <motion.h2
                initial={{ opacity: 0, y: 45 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.35 }}
              >
                Recetas hechas para tí
              </motion.h2>
            </div>
          </header>

          <section className={styles.section}>
            <h2 className={styles.icon__heading} id="empatizando">
              <span>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke-width="1.5"
                  stroke="currentColor"
                >
                  <motion.path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    d="M15 19.128a9.38 9.38 0 002.625.372 9.337 9.337 0 004.121-.952 4.125 4.125 0 00-7.533-2.493M15 19.128v-.003c0-1.113-.285-2.16-.786-3.07M15 19.128v.106A12.318 12.318 0 018.624 21c-2.331 0-4.512-.645-6.374-1.766l-.001-.109a6.375 6.375 0 0111.964-3.07M12 6.375a3.375 3.375 0 11-6.75 0 3.375 3.375 0 016.75 0zm8.25 2.25a2.625 2.625 0 11-5.25 0 2.625 2.625 0 015.25 0z"
                  />
                </svg>
              </span>
              Empatizando
            </h2>
            <p>
              Antes de empezar a realizar diseños, establecer estilos o crear
              prototipos, es importante conocer realmente el problema para el
              cual voy a diseñar una solución. Por ello, realicé una
              investigación de tipo exploratoria, específicamente entrevistas
              semiestructuradas, esto me iba a permitir conocer en profundidad a
              las personas usuarias, identificar sus motivaciones, objetivos y
              necesidades. Los objetivos de mi investigación fueron:
            </p>
            <ul>
              <li>
                Entender qué motiva a las personas usuarias a cocinar de manera
                saludable.
              </li>
              <li>
                Identificar los retos a los que se enfrentan al momento de
                preparar comida saludable.
              </li>
            </ul>
            <p>
              Entrevisté a 7 participantes, 4 mujeres y 3 hombres, con edades
              comprendidas entre los 18 y los 52 años, interesados en mejorar
              sus hábitos alimentarios; algunos de ellos solían cocinar a diario
              y otros únicamente unas pocas veces por semana.
            </p>
            <p>
              Tras realizar y documentar las entrevistas, elaboré un mapa de
              empatía por cada participante, esto me ayudó a organizar y
              sintetizar toda la información recopilada e identificar patrones,
              con esto me fue mucho más fácil la realización de los user
              personas.
            </p>
            <article>
              <h3>User persona</h3>
              <p>
                Basándome en la data obtenida identifiqué 2 grupos principales
                de usuarios, por ello elaboré 2 user personas, para reflejar sus
                características y objetivos. Esto me permitió tener al usuario
                siempre en el foco durante todo el proceso de diseño y guiar mis
                decisiones.
              </p>
              <Image
                src={persona}
                alt="User persona de Ana Vasquez, donde se muestran algunas de sus necesidades y objetivos"
              />
            </article>
            <article>
              <h3>User jorney map</h3>
              <p>
                Para poder visualizar el proceso que las personas usuarias
                estaban atravesando al momento de querer lograr sus objetivos y
                descubrir etapas donde estuvieran teniendo problemas, realicé un
                user journey map tomando en cuenta los user personas creados.
              </p>
              <Image
                src={journeymap}
                alt="Journey map de Ana Vasquez, con los principales problemas que enfrenta al momento de querer cocinar de manera saludable"
              />
            </article>
            <article>
              <h3>Análisis competitivo</h3>
              <p>
                Llevé a cabo un análisis competitivo, donde comparé la
                experiencia de usuario en cada una de las aplicaciones de los
                competidores, fueron 6 competidores. Algunas de las
                oportunidades que identifiqué fueron:
              </p>
              <ul>
                <li>
                  Ofrecer una selección de recetas que hayan sido previamente
                  evaluadas por expertos.
                </li>
                <li>
                  Sugerir recetas que consideren el estado de salud de los
                  usuarios
                </li>
                <li>
                  Crear un diseño simple y atractivo con el que los usuarios
                  disfruten interactuar.
                </li>
              </ul>
            </article>
          </section>
          <section className={styles.section}>
            <h2 className={styles.icon__heading} id="ideacion">
              <span>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke-width="1.5"
                  stroke="currentColor"
                  class="w-6 h-6"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    d="M7.5 8.25h9m-9 3H12m-9.75 1.51c0 1.6 1.123 2.994 2.707 3.227 1.129.166 2.27.293 3.423.379.35.026.67.21.865.501L12 21l2.755-4.133a1.14 1.14 0 01.865-.501 48.172 48.172 0 003.423-.379c1.584-.233 2.707-1.626 2.707-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z"
                  />
                </svg>
              </span>
              Ideación
            </h2>
            <p>
              Después de tener una descripción clara del problema, empecé la
              etapa de ideación. Llevé a cabo una sesión de brainstorming
              utilizando la técnica How Might We (HMW) para generar una buena
              cantidad de ideas; luego utilicé una matriz de priorización
              (Impacto-Esfuerzo) para priorizarlas.
            </p>
            <p>
              En esta etapa también creé los distintos flujos, me apoyé en un
              estudio de card sorting para establecer la arquitectura de
              información y realicé wireframes en baja y media fidelidad.
            </p>
            <article>
              <h3>Userflow</h3>
              <Image
                src={flow}
                alt="Flujo principal de la aplicación donde el usuario tiene como objetivo encontrar una receta para cocinar"
              />
            </article>
            <article>
              <h3>Sitemap</h3>
              <Image
                src={sitemap}
                alt="Diagrama con los diferentes destinos de la aplicación"
              />
            </article>
            <article>
              <h3>Wireframes</h3>
              <motion.div
                className={styles.grid}
                variants={container}
                initial="hidden"
                whileInView="show"
                viewport={{ once: true }}
              >
                <motion.div variants={item}>
                  <Image src={wire1} />
                </motion.div>
                <motion.div variants={item}>
                  <Image src={wire2} />
                </motion.div>
                <motion.div variants={item}>
                  <Image src={wire3} />
                </motion.div>
                <motion.div variants={item}>
                  <Image src={wire4} />
                </motion.div>
                <motion.div variants={item}>
                  <Image src={wire5} />
                </motion.div>
                <motion.div variants={item}>
                  <Image src={wire6} />
                </motion.div>
                <motion.div variants={item}>
                  <Image src={wire7} />
                </motion.div>
              </motion.div>
            </article>
            <article>
              <h3>Pruebas de usabilidad</h3>
              <p>
                Luego de haber creado algunos wireframes llevé a cabo pruebas de
                usabilidad moderada con 5 participantes para saber si lograban
                completar con éxito las principales tareas.
              </p>
              <div className={styles.usability__findings}>
                <div className={styles.usability__description}>
                  <p className={styles.usability__quote}>
                    “Me gustaría que el acceso a la comunidad fuera más fácil” -
                    usuario a
                  </p>
                  <p>
                    A la mayoría de los usuarios les costó encontrar la sección
                    de comunidad
                  </p>

                  <motion.svg
                    width="318"
                    height="581"
                    viewBox="0 0 318 581"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                    className={styles.arrowOne}
                    initial={{ opacity: 0 }}
                    whileInView={{ opacity: 1 }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.45, delay: 0.35 }}
                  >
                    <path
                      d="M13.0268 580.046C65.7316 573.499 115.49 551.566 155.428 516.539C196.021 481.184 224.501 432.735 236.94 380.685C248.398 332.563 249.053 273.966 219.263 231.736C204.859 211.44 184.236 196.709 160.011 190.489C136.769 184.597 111.562 185.906 88.9741 194.09C41.507 211.44 10.0805 257.598 2.22393 306.374C-1.70438 331.253 -1.37702 358.424 11.0626 381.012C24.4843 405.564 51.6552 416.039 77.5165 421.277C126.293 431.098 178.67 421.932 221.554 396.725C265.093 371.191 296.192 328.962 309.941 280.513C323.363 232.718 319.435 180.996 296.847 136.802C275.241 94.2454 237.595 60.2001 193.729 41.5406C183.253 36.9576 172.123 33.6841 160.993 31.0652C150.845 28.7737 146.262 44.4869 156.737 46.7784C199.294 55.9444 237.922 81.1511 264.439 115.524C291.937 151.206 304.704 195.399 300.775 240.248C297.174 285.096 276.878 328.635 243.815 359.406C210.752 390.178 165.576 407.528 120.401 408.51C97.8128 408.837 73.9156 405.564 53.2919 396.725C42.4891 391.815 32.6683 384.94 26.4485 374.792C20.8834 365.299 17.9372 354.496 16.9551 343.366C13.0268 299.172 31.6862 250.723 67.3684 223.88C101.414 198.346 152.154 194.745 186.854 220.933C224.173 249.086 230.721 302.446 226.138 345.657C221.227 394.761 200.604 442.556 168.522 479.874C136.769 516.866 93.8845 543.709 46.7448 556.804C35.6146 559.75 24.157 562.369 12.6994 563.678C8.44375 564.333 4.51545 566.952 4.51545 571.862C4.8428 575.791 8.77111 580.374 13.0268 580.046Z"
                      fill="black"
                    />
                    <path
                      d="M181.944 1.27542C174.415 5.85845 166.885 10.7688 160.011 15.6792C156.083 18.2981 152.482 21.2443 148.881 24.1906C145.28 26.8094 142.006 29.7557 140.369 34.0113C136.441 43.8321 145.935 52.6708 151.5 59.8727C157.065 67.0746 162.957 73.6218 169.177 80.169C176.706 87.6982 188.164 76.2407 180.635 68.7114C175.397 63.4737 170.486 57.9086 165.903 52.3435C163.612 49.7246 161.648 46.7784 159.356 44.1595C158.374 42.85 157.065 41.2132 156.083 39.9038C155.755 39.5764 155.428 38.9217 155.101 38.5943C155.101 38.9217 155.101 39.2491 155.428 39.5765C155.428 40.2312 155.101 40.5586 155.101 41.2133C155.428 40.5586 155.755 40.2312 155.428 40.5585C160.338 37.2849 165.903 32.3745 171.141 28.4462C177.361 24.1905 183.581 19.9349 190.128 16.0066C198.967 9.78676 190.783 -4.28968 181.944 1.27542Z"
                      fill="black"
                    />
                  </motion.svg>
                </div>
                <motion.div
                  initial={{ opacity: 0, y: 50 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.45 }}
                >
                  <Image className={styles.usability__img} src={wireframeOne} />
                </motion.div>
              </div>
              <div
                className={`${styles.usability__findings} ${styles.reverseFlow}`}
              >
                <motion.div
                  initial={{ opacity: 0, y: 50 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.45 }}
                >
                  <Image className={styles.usability__img} src={wireframetwo} />
                </motion.div>
                <div className={styles.usability__description}>
                  <p className={styles.usability__quote}>
                    “No se donde encontrar el total de calorías consumidas” -
                    usuario b
                  </p>
                  <p>
                    Para la mayoría no es claro como visualizar su ingesta
                    diaria de calorías
                  </p>
                  <motion.svg
                    width="364"
                    height="367"
                    viewBox="0 0 364 367"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                    className={styles.arrowTwo}
                    initial={{ opacity: 0 }}
                    whileInView={{ opacity: 1 }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.45, delay: 0.35 }}
                  >
                    <path
                      d="M346.338 4.72951C355.663 37.4398 343.553 70.8295 327.324 100.414C312.907 126.185 295.324 150.599 275.693 173.36C236.681 218.123 187.783 256.342 132.838 285.362C101.912 301.64 68.8936 315.27 34.5868 325.221C25.945 327.836 21.7531 315.818 30.4057 313.451C89.2499 296.213 144.259 268.684 191.585 233.271C238.639 198.119 278.583 155.308 307.568 107.245C325.488 77.5873 342.607 42.4868 332.947 8.54617C331.962 5.35213 333.784 1.78748 337.406 0.63473C341.038 -0.269512 345.353 1.53548 346.338 4.72951Z"
                      fill="black"
                    />
                    <path
                      d="M91.6846 208.965C73.9817 237.119 56.5714 265.51 38.8685 293.664C36.7533 296.992 34.9092 300.06 32.794 303.388C30.9499 306.456 28.2602 309.56 27.2833 313.088C25.7857 317.635 31.5203 319.627 35.8025 320.686C52.389 325.446 69.4962 329.186 86.625 333.424C106.323 338.298 126.032 343.42 145.73 348.293C154.294 350.412 151.157 362.748 142.582 360.38C123.74 355.719 104.899 351.057 86.0464 346.147C68.0612 341.697 49.8156 337.757 32.08 332.55C24.925 330.37 17.4452 327.208 14.3465 320.869C10.6194 313.063 15.3706 305.388 19.601 298.731C28.843 283.89 38.085 269.049 47.327 254.208C57.8816 237.069 68.4469 220.179 79.2834 203.028C83.5031 196.123 95.8935 201.811 91.6846 208.965Z"
                      fill="black"
                    />
                  </motion.svg>
                </div>
              </div>
            </article>
          </section>
          <section className={styles.section}>
            <h2 className={styles.icon__heading} id="refinando">
              <span>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke-width="1.5"
                  stroke="currentColor"
                  class="w-6 h-6"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L6.832 19.82a4.5 4.5 0 01-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 011.13-1.897L16.863 4.487zm0 0L19.5 7.125"
                  />
                </svg>
              </span>
              Refinando
            </h2>
            <p>
              Apliqué los insights obtenidos en la etapa anterior para mejorar
              los diseños
            </p>
            <article className={styles.refine}>
              <div className={styles.refine__container}>
                <Image src={refineOne} />
                <motion.svg
                  width="458"
                  height="164"
                  viewBox="0 0 458 164"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                  className={styles.refine__arrow}
                  initial={{ opacity: 0, x: "-100%" }}
                  whileInView={{ opacity: 1, x: "-50%" }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.45, delay: 0.35 }}
                >
                  <path
                    d="M0.680119 30.0017C15.1205 60.5063 46.1015 77.3618 77.6811 88.6649C105.401 98.3262 134.608 104.887 164.268 108.864C222.906 116.419 284.678 112.576 344.96 97.8919C378.854 89.5851 412.582 77.9259 444.867 62.6772C453.07 58.9169 448.34 47.2031 440.291 51.1555C384.804 77.1842 325.451 93.0206 266.7 97.9146C208.324 102.824 150.265 97.3365 96.9941 80.7029C64.0965 70.4622 28.2322 55.6416 13.2374 23.9995C11.8838 20.9713 8.17844 19.5217 4.70332 21.0552C1.38302 22.7809 -0.673533 26.9735 0.680119 30.0017Z"
                    fill="#A97612"
                  />
                  <path
                    d="M325.783 13.8513C357.532 23.1165 389.216 32.751 420.965 42.0162C424.735 43.0967 428.131 44.1622 431.901 45.2427C435.296 46.3082 439.351 46.8425 442.397 48.8234C446.502 51.2184 443.502 56.4884 440.981 60.1049C431.645 74.6006 421.252 88.6821 411.167 103.148C399.57 119.783 388.128 136.611 376.531 153.247C371.489 160.479 381.931 167.589 386.818 160.165C397.911 144.252 409.004 128.34 419.942 112.236C430.53 97.0467 441.648 82.0648 451.553 66.4766C455.496 60.1291 459.041 52.8363 457.212 46.0715C454.894 37.8001 446.295 35.2249 438.755 33.0639C422.086 28.1207 405.418 23.1774 388.749 18.2341C369.589 12.4475 350.583 6.85284 331.203 1.24325C323.508 -1.10982 317.933 11.3061 325.783 13.8513Z"
                    fill="#A97612"
                  />
                </motion.svg>
              </div>
              <p>
                Agregué una pantalla de introducción para orientar a los
                usuarios sobre las principales características de la aplicación,
                también cambié la ubicación del consumo diario de calorías para
                hacerlo más fácil de encontrar.
              </p>
            </article>
            <article className={styles.refine}>
              <div className={styles.refine__container}>
                <Image src={refineTwo} />
                <motion.svg
                  width="458"
                  height="164"
                  viewBox="0 0 458 164"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                  className={styles.refine__arrow}
                  initial={{ opacity: 0, x: "-100%" }}
                  whileInView={{ opacity: 1, x: "-50%" }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.45, delay: 0.35 }}
                >
                  <path
                    d="M0.680119 30.0017C15.1205 60.5063 46.1015 77.3618 77.6811 88.6649C105.401 98.3262 134.608 104.887 164.268 108.864C222.906 116.419 284.678 112.576 344.96 97.8919C378.854 89.5851 412.582 77.9259 444.867 62.6772C453.07 58.9169 448.34 47.2031 440.291 51.1555C384.804 77.1842 325.451 93.0206 266.7 97.9146C208.324 102.824 150.265 97.3365 96.9941 80.7029C64.0965 70.4622 28.2322 55.6416 13.2374 23.9995C11.8838 20.9713 8.17844 19.5217 4.70332 21.0552C1.38302 22.7809 -0.673533 26.9735 0.680119 30.0017Z"
                    fill="#A97612"
                  />
                  <path
                    d="M325.783 13.8513C357.532 23.1165 389.216 32.751 420.965 42.0162C424.735 43.0967 428.131 44.1622 431.901 45.2427C435.296 46.3082 439.351 46.8425 442.397 48.8234C446.502 51.2184 443.502 56.4884 440.981 60.1049C431.645 74.6006 421.252 88.6821 411.167 103.148C399.57 119.783 388.128 136.611 376.531 153.247C371.489 160.479 381.931 167.589 386.818 160.165C397.911 144.252 409.004 128.34 419.942 112.236C430.53 97.0467 441.648 82.0648 451.553 66.4766C455.496 60.1291 459.041 52.8363 457.212 46.0715C454.894 37.8001 446.295 35.2249 438.755 33.0639C422.086 28.1207 405.418 23.1774 388.749 18.2341C369.589 12.4475 350.583 6.85284 331.203 1.24325C323.508 -1.10982 317.933 11.3061 325.783 13.8513Z"
                    fill="#A97612"
                  />
                </motion.svg>
              </div>
              <p>
                La comunidad se añadió a la barra de navegación inferior para
                facilitar su acceso.
              </p>
            </article>
            <article>
              <h3>Pantallas principales</h3>
              <motion.div
                className={styles.grid}
                variants={container}
                initial="hidden"
                whileInView="show"
                viewport={{ once: true }}
              >
                <motion.div variants={item}>
                  <Image src={final1} />
                </motion.div>
                <motion.div variants={item}>
                  <Image src={final2} />
                </motion.div>
                <motion.div variants={item}>
                  <Image src={final3} />
                </motion.div>
                <motion.div variants={item}>
                  <Image src={final4} />
                </motion.div>
                <motion.div variants={item}>
                  <Image src={final5} />
                </motion.div>
                <motion.div variants={item}>
                  <Image src={final6} />
                </motion.div>
                <motion.div variants={item}>
                  <Image src={final7} />
                </motion.div>
                <motion.div variants={item}>
                  <Image src={final8} />
                </motion.div>
              </motion.div>
            </article>
          </section>
          <section>
            <h2 id="aprendido">Lo que aprendí</h2>
            <ul>
              <li>
                Al momento de diseñar es importante conocer cuáles son los
                objetivos de nuestros usuarios al usar nuestro producto, para
                crear funcionalidades que les permitan alcanzarlos de una manera
                fácil y sencilla.
              </li>
              <li>
                El diseño visual es valioso para generar un producto que sea
                atractivo, pero no lo es todo, hay otros aspectos que son
                fundamentales, como la funcionalidad y la usabilidad. De nada
                sirve hacer un producto que se vea bien, pero que no logra
                satisfacer alguna necesidad de las personas usuarias.
              </li>
            </ul>
          </section>
          <section className={styles.nextSteps}>
            <h2 id="proximo">Próximos pasos</h2>
            <ul>
              <li>
                Realizar una segunda ronda de pruebas de usabilidad para evaluar
                los wireframes de alta fidelidad.
              </li>
              <li>Llevar a cabo una evaluación de la accesibilidad.</li>
            </ul>
          </section>
        </div>
      </Layout>
      <Footer />

      <MobileNav />
    </>
  );
}
